# Generated by Django 3.2.4 on 2021-06-02 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_newsitem_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsItem',
        ),
    ]
