# Generated by Django 3.2.4 on 2021-06-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210602_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='phones',
            name='new_device',
            field=models.BooleanField(default=True),
        ),
    ]
