# Generated by Django 3.2.4 on 2021-06-02 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_laptop_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='original_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
