# Generated by Django 3.2.4 on 2021-06-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_laptop_original_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='phones',
            name='original_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
