# Generated by Django 3.2.4 on 2021-06-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_phones_original_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='new_device',
            field=models.BooleanField(default=False),
        ),
    ]
