# Generated by Django 3.2.4 on 2021-06-02 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_laptop_new_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chargers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('discount', models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Headphones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('discount', models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Accessories',
            new_name='Batteries',
        ),
    ]
