# Generated by Django 3.2.4 on 2021-06-02 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210602_2340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batteries',
            options={'verbose_name_plural': 'Batteries'},
        ),
        migrations.AlterModelOptions(
            name='chargers',
            options={'verbose_name_plural': 'Chargers'},
        ),
        migrations.AlterModelOptions(
            name='headphones',
            options={'verbose_name_plural': 'Headphones'},
        ),
        migrations.AlterModelOptions(
            name='phones',
            options={'verbose_name_plural': 'Smart Phones'},
        ),
        migrations.AddField(
            model_name='batteries',
            name='new_device',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batteries',
            name='original_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chargers',
            name='new_device',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chargers',
            name='original_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='headphones',
            name='new_device',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='headphones',
            name='original_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
