# Generated by Django 3.2.4 on 2021-06-03 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210602_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batteries',
            name='discount',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='chargers',
            name='discount',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='headphones',
            name='discount',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='phones',
            name='discount',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
