# Generated by Django 3.2.4 on 2021-06-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20210603_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shirts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('discount', models.CharField(blank=True, max_length=2, null=True)),
                ('original_price', models.FloatField(blank=True, null=True)),
                ('new_device', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('discount', models.CharField(blank=True, max_length=2, null=True)),
                ('original_price', models.FloatField(blank=True, null=True)),
                ('new_device', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Trousers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('discount', models.CharField(blank=True, max_length=2, null=True)),
                ('original_price', models.FloatField(blank=True, null=True)),
                ('new_device', models.BooleanField(default=False)),
            ],
        ),
    ]
