# Generated by Django 3.2.4 on 2021-06-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_shirts_shoes_trousers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('categories', models.CharField(choices=[('1', 'phones'), ('2', 'laptops'), ('3', 'batteries'), ('4', 'chargers'), ('5', 'headphones'), ('6', 'chargers'), ('7', 'shoes'), ('8', 'shirts'), ('9', 'trousers')], default=1, max_length=30, null=True)),
                ('price', models.FloatField()),
                ('discount', models.CharField(blank=True, max_length=2, null=True)),
                ('original_price', models.FloatField(blank=True, null=True)),
                ('new_device', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.DeleteModel(
            name='Batteries',
        ),
        migrations.DeleteModel(
            name='Chargers',
        ),
        migrations.DeleteModel(
            name='Headphones',
        ),
        migrations.DeleteModel(
            name='Laptop',
        ),
        migrations.DeleteModel(
            name='Phones',
        ),
        migrations.DeleteModel(
            name='Shirts',
        ),
        migrations.DeleteModel(
            name='Shoes',
        ),
        migrations.DeleteModel(
            name='Trousers',
        ),
    ]
