# Generated by Django 3.2.4 on 2021-06-07 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210607_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='categories',
            new_name='category',
        ),
    ]
