# Generated by Django 3.2.4 on 2021-06-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_items_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
