# Generated by Django 3.2.4 on 2021-06-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_items_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='category',
            field=models.IntegerField(choices=[(1, 'Phones'), (2, 'Laptops'), (3, 'Batteries'), (4, 'Chargers'), (5, 'Headphones')], default=1),
        ),
    ]
