# Generated by Django 3.2.4 on 2021-06-09 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_rename_user_profile_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
